FROM ros:melodic-perception-stretch

#Workspace to use
RUN mkdir -p root/catkin_ws/src/
RUN /bin/bash -c 'cd /root/catkin_ws'

#Copy code
COPY . root/catkin_ws/src/sdbackground


RUN apt-get update && apt-get install -y ros-melodic-tf2-sensor-msgs ros-melodic-roslint qtbase5-dev

#Launch the compile
RUN /bin/bash -c ' source /opt/ros/melodic/setup.bash \
	&& cd root/catkin_ws\
	&& catkin_make\
	&& catkin_make run_tests\
	&& catkin_make roslint_pointcloud_merger'
