FROM ros:kinetic-perception-jessie

#Workspace to use
RUN mkdir -p root/catkin_ws/src/
RUN /bin/bash -c 'cd /root/catkin_ws'

#Copy code
COPY . root/catkin_ws/src/pointcloud_merger

RUN apt-get update && apt-get install -y ros-kinetic-tf2-sensor-msgs ros-kinetic-roslint qtbase5-dev

#Launch the compile
RUN /bin/bash -c ' source /opt/ros/kinetic/setup.bash \
	&& cd root/catkin_ws\
	&& catkin_make\
	&& catkin_make run_tests\
	&& catkin_make roslint_pointcloud_merger'
