name: Docker Image CI

on:
  push:
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  pull_request:
    branches: [ master ]

jobs:

  build_kinetic:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image kinetic
      run: docker build . --file docker/Dockerfile.kinetic --tag kinetic:$(date +%s)

  build_melodic:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image melodic
      run: docker build . --file docker/Dockerfile.melodic --tag melodic:$(date +%s)
